### ISSUE TITLE
@discardableResult in StubResponse builder functions

### ISSUE THREAD

**Issue by alexanderzaak2211** [JanGorman/Hippolyte#22]
Adding the @discardableResult on builder functions resolves compilation warnings when configuring the responsebuilder in several steps. 
Ex: Result of call to 'stubResponse(withError:)' is unused

**Comment by JanGorman** [comment]
Do you have a sample use case that you could share? I don't have an issue with the change per se but I'm having a hard time to understand your use case. Wouldn't you always want to store the result of the last `.build()` call off into a variable so that you can pass it as response to a request?

**Comment by alexanderzaak2211** [comment]
static func stub(url: String,
                     with jsonFile: String,
                     withError error: NSError? = nil,
                     with method: HTTPMethod = .GET,
                     with statusCode: StatusCode = .success) {

        guard let data = TestUtils.dataFromJSONMock(withName: jsonFile) else {
            XCTFail("Could not access json file '\(jsonFile)'.")
            return
        }
        let responseBuilder = StubResponse.Builder()

        if let error = error {
           _ = responseBuilder
                .stubResponse(withError: error)
        } else {
             let body = data
           _ = responseBuilder
                .stubResponse(withStatusCode: statusCode.rawValue)
                .addBody(body)
        }

        let response = responseBuilder.build()

        var request = StubRequest.Builder()
            .stubRequest(withMethod: method, url: URL(string: url)!)
            .addResponse(response)
            .build()
        request.response = response
        Hippolyte.shared.add(stubbedRequest: request)
    }

In the above function I'm passing an error as an optional argument and use the Builder of the StubResponse on this way. I'm configuring the Builder and don't care about results of every .build() and get the result only in the end.

**Comment by JanGorman** [comment]
👍 Makes sense, thanks for clarifying. Feel free to open a PR with the change, otherwise I'll get it done later today

**Comment by alexanderzaak2211** [comment]
Yes I will create a PR.
