### ISSUE TITLE
stub request not found

### ISSUE THREAD

**Issue by purnendu007** [JanGorman/Hippolyte#4]
I am keen to unit test, getting stub request not found while I have set it up rightly and passing a valid json data as a response.
pasting the error log, please guide me the correct way. Also I am making a request with POST method, but getting the request as GET in the error.

Printing description of error:
▿ Optional<Error>
  ▿ some : No matching stub found for https://testdemo/v0.4/login/
    ▿ request : https://testdemo/v0.4/login/
      ▿ url : Optional<URL>
        ▿ some : https://testdemo/v0.4/login/
      - cachePolicy : 0
      - timeoutInterval : 60.0
      - mainDocumentURL : nil
      - networkServiceType : __ObjC.NSURLRequest.NetworkServiceType
      - allowsCellularAccess : true
      ▿ httpMethod : Optional<String>
        - some : "GET"
      ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
        - some : 0 elements
      - httpBody : nil
      - httpBodyStream : nil
      - httpShouldHandleCookies : true
      - httpShouldUsePipelining : false
(lldb)

**Comment by JanGorman** [comment]
Could you please share the code you're running that is producing the error – it's hard to pinpoint the issue with just the console output
