### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by smacnabb3** [JanGorman/Hippolyte#57]
Hello, I'm getting 'Undefined symbols for architecture x86_64' after adding this framework.  I've cleaned my derived data folder, made sure linker flags have '$(inherited) and made sure build archive arch was set to NO and I can't get this framework to build.  Any ideas?

**Comment by JanGorman** [comment]
Can you share a bit more about how you're integrating the framework (i.e. Carthage, CocoaPods, …) and what the target platform

**Comment by smacnabb3** [comment]
i figured it out, my mistake.
