### ISSUE TITLE
Hippolyte.shared.stop() not working as expected

### ISSUE THREAD

**Issue by ajelden** [JanGorman/Hippolyte#58]
Hello. We are using version 1.2.3 of Hippolyte with Xcode 12.1, macOS Catalina 10.15.7. We are seeing that `Hippolyte.shared.stop()` is not working the way we expect.

We have a test suite that includes tests where we do not want to mock HTTP transactions. Other tests in our test suite use Hippolyte where we do want mocking. Our `tearDown()` function includes the call `Hippolyte.shared.stop()`, but we are seeing tests where we do not want mocking fail with
```
Error Domain=Hippolyte.HTTPStubURLProtocol.NoMatchError Code=1 "(null)" UserInfo={_NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <A5D03C08-843F-451B-9871-633EED5F4DC9>.<35>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <A5D03C08-843F-451B-9871-633EED5F4DC9>.<35>}
```

In the test suite, there are tests that use Hippolyte that execute before the failing test.
If we run the failing test by itself, it passes.

We expected `Hippolyte.shared.stop()` to disable Hippolyte and allow unmocked HTTP transactions. Is that the correct expectation?

**Comment by JanGorman** [comment]
Hi,

Sorry to hear about that. So yes, definitely the correct expectation on your end. I'll take a look – I suspect it's to do with this addition https://github.com/JanGorman/Hippolyte/commit/3f70d9409bc447742467831961739eb79ba7ec0d.

Could you verify if it behaves as expected by reverting to version 1.2.2?

**Comment by ajelden** [comment]
Yes, I can try version 1.2.2. I would need to use Xcode 11 for that, right?

**Comment by JanGorman** [comment]
Should work with Xcode 12 as well

**Comment by ajelden** [comment]
Ok.
Cartfile.resolved shows `github "JanGorman/Hippolyte" "1.2.2"`
I restarted XCode-12, and did Cmd-shift-k to clean the build folder, but running my test suite, I'm seeing the same error.

**Comment by JanGorman** [comment]
Alright, thanks for trying that out though. I'll investigate

**Comment by JanGorman** [comment]
@ajelden Could you test using the branch `unload-hooks` please to see if that resolves the issue?

**Comment by ajelden** [comment]
I'll give it a try.

**Comment by ajelden** [comment]
Sorry, still seeing the same problem.

**Comment by ajelden** [comment]
I found a way to reproduce what I'm seeing. The attached test case (you'll need to change the file extension from .txt to .swift) contains a function, `runUnmockMockUnmockTest()`, that runs an unmocked HTTP transaction, followed by a mocked HTTP transaction ("Stubbed" is probably better--sorry), followed by another unmocked HTTP transaction.

The unmocked transaction returns 321 bytes.
The mocked transaction returns 9 bytes.

The `runUnmockMockUnmockTest()` function is called 3 times.

Running the test case as-is succeeds. The test runs as
 - umnocked-MOCKED-unmocked
 - umnocked-MOCKED-unmocked
 - umnocked-MOCKED-unmocked

...as expected.


But if you uncomment the call to `Hippolyte.shared.stop()` in `tearDown()`, the test runs as
 - umnocked-MOCKED-unmocked
 - MOCKED-unmocked-MOCKED
 - umnocked-MOCKED-unmocked

...causing the second run to fail.

I will try removing `Hippolyte.shared.stop()` from the `tearDown()` function in my other test case to see if that helps resolve my problem.

[HippolyteStopStartTests.txt](https://github.com/JanGorman/Hippolyte/files/5538928/HippolyteStopStartTests.txt)

**Comment by ajelden** [comment]
Oh, shoot. I only see the above behavior in the `unload-hooks` branch, not in `master`--must be something wrong in my code base. Thanks for looking into this. I may do some more experimenting, but I think this issue can be closed.

**Comment by JanGorman** [comment]
thanks for investigating further! Feel free to raise another issue if you find anything
