### ISSUE TITLE
Bring 1.4.1 to cocoapods

### ISSUE THREAD

**Issue by cornelius-behrend** [JanGorman/Hippolyte#66]
Do you have any plans to bring 1.4.1 to cocoapods? This would be awesome ☺️

**Comment by JanGorman** [comment]
Hey, thanks for raising the issue. Must have been an oversight at the time. I wanted to `pod trunk push` it now but I get an error
```
Validating podspec
 -> Hippolyte (1.4.1)
    - ERROR | [iOS] unknown: Encountered an unknown error (unexpected token at '2024-07-11 16:06:50.187 simctl[24710:279064] getMetalPluginClassForService: Failed to find bundle for accelerator bundle named: AGXMetalA12 errno: 0
') during validation.
```

that I can't make much sense of. Could I add you as pod collaborator and let you try to push it to trunk?

**Comment by cornelius-behrend** [comment]
Hey @JanGorman, thanks for your answer and yeah, lets do this ☺️

**Comment by JanGorman** [comment]
Great, can you send me the email address I should use please. You can find my contact here https://github.com/JanGorman/Hippolyte/blob/master/Hippolyte.podspec#L15 😉 if you prefer not posting it on github

**Comment by JanGorman** [comment]
@cornelius-behrend Thanks for all your help so far. I added you as a cocoa pods owner just now. If you now clone the repository and from its root directory run `pod trunk push` it hopefully should work.

**Comment by cornelius-behrend** [comment]
1.4.1 is now available 🥳 @JanGorman I enjoyed our collaboration on this ☺️ Thanks for sharing your library with the world! Feel free to close the issue.

**Comment by JanGorman** [comment]
Awesome, thank you 🙏
