### ISSUE TITLE
Carthage compatible

### ISSUE THREAD

**Issue by iosdevmax** [JanGorman/Hippolyte#7]
Just a question

Is it Carthage compatible? 
If not, any plans for the compatibility in the nearest future?

**Comment by JanGorman** [comment]
Hi there,

Since the `Hippolyte.xcodeproj` is on the top level directory and the scheme shared it actually already should be Carthage compatible. It's just not highlighted in the README

try `github "JanGorman/Hippolyte"`

If it's fine I can update the README accordingly.

**Comment by iosdevmax** [comment]
great, will do, thanks
I'll let you know if it's alright

**Comment by amadeu01** [comment]
I got those errors when I was trying to use the library with Carthage

<img width="953" alt="image" src="https://user-images.githubusercontent.com/11631092/40821055-cd0b5d04-653a-11e8-9932-2984e620be8b.png">

**Comment by amadeu01** [comment]
Sorry, nevermind.

I forgot to add the library to the `Link Binary with Libraries` on the test client

<img width="760" alt="image" src="https://user-images.githubusercontent.com/11631092/40821172-a4feb940-653b-11e8-83ae-6a98ef56f210.png">

**Comment by amadeu01** [comment]
It worked fine for me.
I'm using Alamofire and it returned what I stubbed.

Thanks! Great library

**Comment by JanGorman** [comment]
Great to hear. And thanks ☺️
