### ISSUE TITLE
Question: Is that possible to stub a connection error ? or Bandwidth Throttling?

### ISSUE THREAD

**Issue by amadeu01** [JanGorman/Hippolyte#8]
Hi,

I'm using the library to write test the stub the request response with some already saved responses in the tests code base. But, I would like to test for poor bandwidth and error connections, would that be possible with Hippolyte?

**Comment by JanGorman** [comment]
Error responses can be mocked using `StubResponse(statusCode: …)`. If you return anything outside of the 200 range that will trigger your error handling.
Anything else such as a slow connection are out of scope for such a library and probably more of a UI challenge. The response will arrive eventually, it's just a question if the user of an app stays engaged long enough to care ;)

**Comment by amadeu01** [comment]
@JanGorman  thanks for your reply.

I was willing if I could make some error happen such as Error connection, server not available...
But, I guess I'll have to make it in another way. Anyway, I appreciate your help and your time. Thanks.
